### ISSUE TITLE
Приватный ключ для ноды

### ISSUE THREAD

**Issue by plahov** [relictumblockchain/RPHPSDK#1]
Подскажите:

1. я сгенерировал ключи 

> openssl genrsa -out private.key 2048
> openssl rsa -in private.key -pubout -out key.pub

2. Куда и как на серваке с белой нодой положить ключи, чтобы нода могла их использовать для расшифровки подписи при запросах?

Предполагаю, что надо как-то указывать в файле .config - подскажите формат

**Comment by relictumblockchain** [comment]
Переименуйте файл key.pub, чтобы его название соответствовало uri вашего контракта без "system://", и с "-" в качестве разделителя и перенесите его в директорию ноды.
Пример: ваш контракт system://payments/mycontract - тогда ключ должен называться payments-mycontract.pub

**Comment by plahov** [comment]
Спасибо, удалось реализовать.
