### ISSUE TITLE
Stage.net и Main.net

### ISSUE THREAD

**Issue by plahov** [relictumblockchain/RPHPSDK#2]
Подскажите как при тестировании указать ноде работать в тестовой сети?

И как при необходимости потом переключиться на основную сеть в боевой режим?

**Comment by plahov** [comment]
Я создал в Stage.net платежный контракт, но в эксплоере на вкладке Stage.net в разделе контракты - самого созданного контракта не видно, или он не будет считаться смарт-контрактом, а будет работать под контрактом system://payments?

**Comment by relictumblockchain** [comment]
Вы должны работать с тем контрактом, который создали.

**Comment by plahov** [comment]
Спасибо, удалось реализовать в части выставления счетов.
