### ISSUE TITLE
Параметры для создания счета

### ISSUE THREAD

**Issue by plahov** [relictumblockchain/RPHPSDK#3]
Какие необходимо передать обязательные/необязательные параметры [$params] в метод:
`Relictum\RPHPSDK\Request doPaymentCreate(string $contract, array $params)`

**Comment by relictumblockchain** [comment]
[
"payment" => 1, // Номер счёта, для дальнейшей работы
"addressfrom"=> "fJgElq2WvcSncsfNgKhFmr3XwdTodtgR", // Адрес, которому будет выставлен счёт
 "addressto"=> "3VeNhgDVkvX9CSVn4WfPihEWlwYADTWp", // Адрес получателя платежа
 "token"=> "usdr", // Токен платежа
 "amount"=> 30.42 // Сумма
]

Вместо addressfrom/addressto можно использовать accountfrom/accountto. В таком случае, передаваться должны не адреса, а id аккаунтов.

**Comment by plahov** [comment]
При попытке отправить запрос с указанными вами параметрами - прилетает ошибка `Value 'data' not found`

Переопределяю параметры включив все, что вы указали вложенным массивом в параметр **data**
```
[
    "data" => ["ваши параметры со моими значениями"]
]
```
Прилетает ошибка `unable load ssl library`, на сколько я понимаю нода не может получить доступ к ssl библиотеке в окружении **Delphi** - Win 10 Pro Версия 21H2 Сборка OC 19044.1466

Подскажите, если не сложно: как решить проблему с ssl на стороне сервера.

**Comment by plahov** [comment]
С ошибкой `unable load ssl library` проблему решил [(решение)](https://nstecnologia.com.br/blog/could-not-load-ssl-library/)

Запрос на выставление счета вернул ответ:
```
_fields: array:1 [
    0 => "success"
  ]
+"success": true
```
Но при этом счет не выставлен, запрос через метод **checkPayments** с **index** = 0 - возвращает ответ без объектов.

**Comment by plahov** [comment]
Все получилось. Спасибо.
