### ISSUE TITLE
Перевод токенов 

### ISSUE THREAD

**Issue by plahov** [relictumblockchain/RPHPSDK#5]
Для перевода как я понимаю необходимо использовать отдельные ключи, не от платежного контракта.
`Relictum\RPHPSDK\Request doTransfer(array $params)`

1. Подскажите какой формат (название.pub) их хранения в ноде.

2. Как переводить токены в рамках сети (тестовая | основная) если это возможно?

3. Есть ли возможность отправлять токены (не выставление счета) в рамках платежного контракта, чтобы использовать один ключ для выставления счета и перевода из ноды токенов?

4. Какие параметры необходимо указывать?

```
 [
    'data' => [ 
	 'token' => 'USDR', // token
	'amount' => 20, // amount of tokens
	 'data' => [
		'account' => 1 // ID of the recipient node
	 ]
      ]
 ]
```

**Comment by relictumblockchain** [comment]
1. Для метода transfer это будет transfer.pub в корне директории с нодой.
2. Переводить токены можно посредством запроса transfer (метод doTransfer) или запроса user/transfer (метод doUserTransfer) web user api (должен быть включен в ноде).
3. Нет. Но при желании, вы можете продублировать один и тот же ключ с названиями transfer.pub и payments-_contract_.pub, тогда для отправки все запросы можно будет подписывать одним и тем же ключом.
4. Собственно, а в чём вопрос? Именно эти.

**Comment by plahov** [comment]
А как определять тестовая сеть и основная сеть - как их отделить?
Сейчас в тестировании и хочется отправлять токены из тестовой сети.

Или это зависит от того какая сеть сейчас в ноде включена?

**Comment by plahov** [comment]
Как включить web user api? (должен быть включен в ноде)

**Comment by plahov** [comment]
> 4. Собственно, а в чём вопрос? Именно эти.

Получаю ошибку: `account or address not found`
-- --
Если изменить массив на 
```
[
    'data' => [ 
	'token' => 'USDR', // token
	'amount' => 20, // amount of tokens
        'account' => 10191 // ID of the recipient node
      ]
 ]
```
то получаю ошибку `The specified file was not found` - ключ transfer.pub лежит в корне ноды

**API логи**
```
[25.01.2022 14:27:55.506] THTTPServerClient(2624) open
[25.01.2022 14:27:55.506] Remote Host: 15.33.54.134:42738
[25.01.2022 14:27:55.506] POST /api/transfer HTTP/1.1
[25.01.2022 14:27:55.506] {"account": 10191, "amount": 20, "token": "USDR"}
[25.01.2022 14:27:55.521] {"success": false, "error": "The specified file was not found"}
[25.01.2022 14:27:55.521] 200 OK
[25.01.2022 14:27:55.521] THTTPServerClient(2624) destroy
```

**Comment by relictumblockchain** [comment]
Извиняюсь. Перепутал.
accountto или addressto, в зависимости от того, хотите вы указать id, или адрес ноды.

**Comment by relictumblockchain** [comment]
> Как включить web user api? (должен быть включен в ноде)

Необходимо прописать в конфигурации:

{
	"webaccess": {
		"active": true
		}
}

**Comment by plahov** [comment]
> Извиняюсь. Перепутал. accountto или addressto, в зависимости от того, хотите вы указать id, или адрес ноды.

Даже внеся изменения в массив по вашей рекомендации, получаю ошибку.

Получаю `{"success": false, "error": "account or address not found"}` в случае если отсылаю любой из 8-ми вариантов:
```
1. {"amount": 20, "token": "USDR", "data": {"accountto": 10191}}
2. {"amount": 20, "token": "USDR", "data": {"addressto": 'bgNnlxJgFRX0U36fchPomyKhHSY1f80X'}}
3. {"amount": 20, "token": "USDR", "data": {"account": 10191}}
4. {"amount": 20, "token": "USDR", "data": {"address": 'bgNnlxJgFRX0U36fchPomyKhHSY1f80X'}}
5. {"accountto": 10191, "amount": 20, "token": "USDR"}
6. {"addressto": 'bgNnlxJgFRX0U36fchPomyKhHSY1f80X', "amount": 20, "token": "USDR"}
7. {"account": 10191, "amount": 20, "token": "USDR"}
8. {"address": 'bgNnlxJgFRX0U36fchPomyKhHSY1f80X', "amount": 20, "token": "USDR"}
```

-- --
Получаю `{"success": false, "error": "The specified file was not found"}`  в случае если отсылаю любой из 2-х вариантов: 
```
1. {"account": 10191, "amount": 20, "token": "USDR"}
2. {"address": 'bgNnlxJgFRX0U36fchPomyKhHSY1f80X', "amount": 20, "token": "USDR"}
```

**Comment by plahov** [comment]
> > Как включить web user api? (должен быть включен в ноде)
> 
> Необходимо прописать в конфигурации:
> 
> { "webaccess": { "active": true } }

Ошибка: `web access disabled`

В директории `networks/mainnet` файл `.config`

```
{
    "net": { "ip4": "255.255.255.0" }, - адрес для примера
    "webaccess": { "active": true }
}
```
Тот же результат если переносить этот файл в директорию `networks/testnet`

Ноду перезагружал

**Comment by relictumblockchain** [comment]
Извиняюсь. Уточнил информацию.

В методе transfer название токена указывается как usdr (строчными буквами).
Также проверьте, чтобы адрес получателя находился в той же сети, что и ваша нода. 

Для включения webuser api сейчас такие настройки.
"webuser": {   "enabled": true,   "rw_pkey": false   }

**Comment by plahov** [comment]
Результат не поменялся.

Ок, давайте я расскажу как у меня все настроено:

Настроена белая нода - есть статичный ip, он указан в файле `networks/mainnet/.config` - статус ноды `БЕЛАЯ` как в тестовой так и в основной сети.

Нода отзывается по 80 порту через `http://-IP-/api`

-- -- 

### Выставление счетов:
Запущена тестовая сеть, в тестовой сети создан платежный контракт, в корне ноды лежит ключ `payments-<CONTRACT-NAME>.pub`. Счета через API выставляются и также проверяются на 5 баллов - здесь проблем не возникло - все зашло с первого раза.

-- --

### Отправка токенов с ноды:
Запущена тестовая сеть, в корне ноды лежит ключ `transfer.pub`, формирую массив запроса и вместе с авторизацией направляю этот запрос через метод `doTransfer()` в запросе лежат параметры `token, amount и account | address`

Значения параметров `params` пробовал:
```
token|symbol: USDR|usdr|Usdr
amount: [0-9]+
account|accountto|to: [0-9]+
address|addressto|to: [a-zA-Z0-9]{32}
```

Все эти значения направлял в одномерном массиве`[params]`, так и оборачивал во вложенный массив `data => [params]` - потому что приходило исключение с указанием отсутствия значения `data`. 

Пробовал и как в примере у вас указано вложенным массивом `data` указывал только `account|address|accountto|addressto|to` т.е.

```
token|symbol: USDR|usdr|Usdr
amount: [0-9]+
data: [
    account|accountto|to: [0-9]+
    address|addressto|to: [a-zA-Z0-9]{32}
]
```

Исключения в основном это `The specified file was not found` или `account or address not found`

Адреса или аккаунты точно находятся в той сети, при которой делаю запросы, потому как счета на них выставляются на ура в нужной сети.


-- --

Заменил настройки `networks\testnet\.config`

```
{
    "net": { "ip4": "255.255.255.0" }, - адрес для примера
    "webuser": { "enabled": true, "rw_pkey": false }
}
```

Результат:
`D:\RNODE\networks\testnet\webaccounts\<ACCOUNT_ID> (Relictum\\RPHPSDK\\Exceptions\\NodeRequestException(code: 0): Закрытый ключ не найден`

Методом исключения понял, что спотыкается на методе `doUserLogin()`, пример использовал из [ваших](https://github.com/relictumblockchain/RPHPSDK/blob/77c929b55c7ec93fa9232e71935c18a1b79e05b7/examples/user.php) 

Если это web авторизация по логину и паролю - не понимаю какой ему нужен ключ

-- --
### Вопросы
1. Огромная просьба, подскажите как правильно формировать массив запроса - лучше _живым_ примером или еще лучше выдержкой из логов api ноды - какой в ноду приходит запрос в формате JSON. 

2. Еще раз уточните правильно ли назван файл .pub для transfer (настораживает ошибка `The specified file was not found`)
 
3. И еще попутно вопрос на будущее, про `wait_id` и запрос `transfer/status` - они будут работать при запросах через `.pub` или только через `webUser`?

4. В каких случаях может быть возвращен `wait_id`?

5. Насколько безопасно использовать webUser авторизацию? По логам видно, что на ноду ломятся достаточно много запросов с подстановкой uri, также есть и shell запросы 

6. Как при `webUser` авторизации использовать настройку `rw_pkey: true`? Она как-то сможет обезопасить этот вид авторизации?

7. Какой ключ ему нужен `Закрытый ключ не найден` если в настройках авторизации weUser `"rw_pkey": false `?

**Comment by kRen0** [comment]
Извиняюсь ещё раз. Файл должен называться transfer2.pub, другой только для токена GTN.
Также, то вот пример с полностью рабочими transfer и user-transfer:
https://mega.nz/file/8lMngIzI#oiMIBU2cb4Nl9ST_VUOgPprxEM-AffQhG3NhjpQeR0A

4. Практически всегда, если не установлен хедер keep-alive.
5. Я бы рекомендовал использовать для отправки собственных средств ресурса исключительно doTransfer().
6. Нет. Данная настройка отвечает за включения доступа к импорту/экспорту приватных ключей по api.
7. Пользователь должен быть создан через webuser-api, либо его приватный ключ должен быть импортирован через метод pkey/import.

**Comment by plahov** [comment]
### Огонь!!!

Все получилось. 

Спасибо за примеры, прям с нодой))) - неожиданно!

Единственное пожелание - это чтобы в методе `doTransfer()` в случае успешной транзакции - возвращался не просто `"success": true`, а еще бы `hash` транзакции.

Ребята, спасибо.
